Add dethy
Soumil07/godfather pull request #29
Opened 2020-10-17 17:30 UTC by MeDerpWasTaken

Add's the dethy setup along with the dethy cops

2020-10-17 17:41 UTC, MeDerpWasTaken commented
oops I forgot a description

2020-10-18 05:22 UTC, Soumil07 requested changes
Additionally, Goons shouldn't be able to kill N1 on Dethy. You should add an appropriate check there in `Goon#canUseAction`

2020-10-18 05:22 UTC, Soumil07 commented on src/lib/mafia/roles/town/dethy/Insane_Cop.ts
> +
this can be `@mafia` instead of `@root/lib/mafia`

2020-10-18 05:22 UTC, Soumil07 commented on src/lib/mafia/roles/town/dethy/Insane_Cop.ts
> +	}
You can remove this since it's included in the base role.

2020-10-18 05:22 UTC, Soumil07 commented on src/lib/mafia/roles/town/dethy/Insane_Cop.ts
> +		return innocence;
This should return `!innocence`, since Insane Cops always show the opposite result.

2020-10-18 05:22 UTC, Soumil07 commented on src/lib/mafia/roles/town/dethy/Naive_Cop.ts
> +import Townie from "@root/lib/mafia/mixins/Townie";
Same as above.

2020-10-18 05:22 UTC, Soumil07 commented on src/lib/mafia/roles/town/dethy/Naive_Cop.ts
> +	innocenceModifer(innocence: boolean) {
This needs to be `public innocenceModifier`

2020-10-18 05:22 UTC, Soumil07 commented on src/lib/mafia/roles/town/dethy/Paranoid_Cop.ts
> +import Townie from "@root/lib/mafia/mixins/Townie";
Same as above.

2020-10-18 05:22 UTC, Soumil07 commented on src/lib/mafia/roles/town/dethy/Paranoid_Cop.ts
> +	innocenceModifer(innocence: boolean) {
Same as above.

2020-10-18 14:26 UTC, MeDerpWasTaken commented
> Additionally, Goons shouldn't be able to kill N1 on Dethy. You should add an appropriate check there in `Goon#canUseAction`

Where would I add this?

2020-10-18 18:25 UTC, MeDerpWasTaken commented
I found a decent amount of bugs so I'm closing this for now

2020-10-18 18:25 UTC, closed without merging