feat: add Serial Killer
Soumil07/godfather pull request #33
Opened 2020-11-12 15:44 UTC by MeDerpWasTaken

2020-11-12 15:47 UTC, Soumil07 requested changes
Also it looks like you've removed the setUp part of a kill entirely, so please add that too.

2020-11-12 15:47 UTC, Soumil07 commented on src/lib/mafia/factions/neutral/SerialKiller.ts
> +		return aliveSerialKillers.length > 0
This should just check aliveSKs > 0 and aliveOpposing > 0, since technically the SK has to see *everyone* else die.

2020-11-12 15:47 UTC, Soumil07 commented on src/lib/mafia/roles/neutral/Serial_Killer.ts
> +	public actionText = 'stab a player.';
```suggestion
	public actionText = 'stab a player';
```

2020-11-12 15:47 UTC, Soumil07 commented on src/lib/mafia/roles/neutral/Serial_Killer.ts
> +		console.log(record, actions.record);
```suggestion
```
This can go

2020-11-12 16:05 UTC, MeDerpWasTaken commented
> Also it looks like you've removed the setUp part of a kill entirely, so please add that too.

I didn't remove it, I used goon as a template and there isn't any setUp()

2020-11-14 04:00 UTC, Soumil07 requested changes

2020-11-14 04:00 UTC, Soumil07 commented on src/lib/mafia/factions/neutral/SerialKiller.ts
> +import Game from '../../Game';
```suggestion
import Game from '@mafia/Game';
```

2020-11-14 04:00 UTC, Soumil07 commented on src/lib/mafia/factions/neutral/SerialKiller.ts
> +		const aliveOpposingPrs = players.filter(filterOpposingPowerRoles);
This should just check aliveOpposing, not aliveOpposingPrs

2020-11-14 15:36 UTC, Soumil07 approved these changes

2020-11-14 15:37 UTC, merged