Crusader
Soumil07/godfather pull request #62
Opened 2021-01-06 07:44 UTC by Radiating8

whoops, wrong branch

2021-01-06 19:15 UTC, Soumil07 requested changes

2021-01-06 19:15 UTC, Soumil07 commented on src/lib/mafia/roles/town/Crusader.ts
> +		let playerToKill: Player = Array.from(visitors)[Math.floor(Math.random() * visitors.size)];
Use `util.randomArray` here: https://github.com/Soumil07/godfather/blob/master/src/lib/util/utils.ts#L28

2021-01-06 19:15 UTC, Soumil07 commented on src/lib/mafia/roles/town/Crusader.ts
> +		let actionNames = [...playerRecord.keys()];
alternatively, just `const { visitors } = this.player`. For this to work though, you'll have to put Crusader's priority dead last, next to Ambusher.

2021-01-06 19:15 UTC, Soumil07 commented on src/lib/mafia/roles/town/Crusader.ts
> +	public actionConfirmation(target: Player) {
This can be safely removed.

2021-01-06 19:20 UTC, MeDerpWasTaken requested changes
Don't use killed, use something like attacked instead

2021-01-07 16:38 UTC, MeDerpWasTaken approved these changes

2021-01-08 07:40 UTC, Soumil07 approved these changes

2021-01-11 13:51 UTC, merged